import type { Staff } from "./types";

export const mockStaff: Staff[] = [
  {
    id: "STF-001",
    name: "Eleanor Vance",
    phone: "+1-202-555-0184",
    email: "eleanor.v@example.com",
    position: "Lead Developer",
    department: "Engineering",
    photoUrl: "https://picsum.photos/seed/101/100/100",
    status: "active",
  },
  {
    id: "STF-002",
    name: "Marcus Holloway",
    phone: "+1-202-555-0191",
    email: "marcus.h@example.com",
    position: "UI/UX Designer",
    department: "Design",
    photoUrl: "https://picsum.photos/seed/102/100/100",
    status: "active",
  },
  {
    id: "STF-003",
    name: "Chloe Decker",
    phone: "+1-202-555-0145",
    email: "chloe.d@example.com",
    position: "Project Manager",
    department: "Management",
    photoUrl: "https://picsum.photos/seed/103/100/100",
    status: "active",
  },
  {
    id: "STF-004",
    name: "Arthur Morgan",
    phone: "+1-202-555-0162",
    email: "arthur.m@example.com",
    position: "Backend Engineer",
    department: "Engineering",
    photoUrl: "https://picsum.photos/seed/104/100/100",
    status: "inactive",
  },
  {
    id: "STF-005",
    name: "Sadie Adler",
    phone: "+1-202-555-0110",
    email: "sadie.a@example.com",
    position: "QA Tester",
    department: "Quality Assurance",
    photoUrl: "https://picsum.photos/seed/105/100/100",
    status: "active",
  },
  {
    id: "STF-006",
    name: "John Marston",
    phone: "+1-202-555-0129",
    email: "john.m@example.com",
    position: "DevOps Specialist",
    department: "IT Operations",
    photoUrl: "https://picsum.photos/seed/106/100/100",
    status: "active",
  },
];
